include: package:lint_hard/all.yaml
analyzer:
  errors:
    avoid_classes_with_only_static_members: ignore
 

linter:
  rules:
    avoid_print : false  
    # Exclude rules to match pub.dev code.
    lines_longer_than_80_chars: false  
    cascade_invocations: false