#! /usr/bin/env dcli

// ignore: unused_import
import 'dart:io';

import 'package:dcli/dcli.dart';
import 'package:pub_semver/pub_semver.dart';

/// dcli script generated by:
/// dcli create %scriptname%
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///
void main(List<String> args) {
  // We always release using dart 2.12 which requires us
  // to modify some dependencies.

  final sdkVersion = DartSdk().getVersion();
  if (sdkVersion.compareTo(Version.parse('2.12.0')) != 0) {
    printerr(red('You must release using Dart 2.12.0 found: $sdkVersion'));
    exit(1);
  }
}
