#! /usr/bin/env dcli

import 'dart:io';

import 'package:dcli/dcli.dart';
import 'package:onepub/src/onepub_paths.dart';
import 'package:onepub/src/onepub_settings.dart';
import 'package:onepub/src/util/one_pub_token_store.dart';
import 'package:settings_yaml/settings_yaml.dart';

/// dcli script generated by:
/// dcli create %scriptname%
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///
void main(List<String> args) {
  var pathToBin = DartProject.self.pathToBinDir;

  var pathToOnePubExe = join(pathToBin, 'onepub.dart');

  var settings =
      SettingsYaml.load(pathToSettings: OnePubPaths().pathToTestSettings);

  var user = settings.asString('member');

  print('Please login with $user account');

  /// prompt the user to login inot onepub.
  '$pathToOnePubExe login'.run;

  var tokenStore = OnePubTokenStore();
  if (!tokenStore.isLoggedIn) {
    printerr(red('Login Failed. Tests run stopped'));
    exit(1);
  }

  final onepubSettings = OnePubSettings.load();
  var url = onepubSettings.onepubApiUrl;
  final credentials = tokenStore.tokenStore.findCredential(Uri.parse(url));

  if (credentials == null) {
    printerr(red('Unable to find the OnePub token for $url'));
    exit(1);
  }

  var onePubToken = credentials.token;

  settings['OnePubToken'] = onePubToken;
  settings.save();
}
